### ISSUE TITLE
Inconsistent behavior between agent-config on different platforms

### ISSUE THREAD

**Issue by rcbjBlueMars** [hypertrace/pythonagent#214]
## Use Case
Slight inconsistency with how the other in-app agents support configs... the other agents (golang, nginx, java) support both adding the protocol and omitting the protocol from the reporting.endpoint. In python's case, it only supports endpoints prefixed with the protocol. If you drop the protocol, then the spans fail silently to be sent to the platform

so this works...
```
service_name: "python-svc"
reporting:
  endpoint: "http://localhost:4317"
  trace_reporter_type: "OTLP"
```
but this doesnt:
```
service_name: "python-svc"
reporting:
  endpoint: "localhost:4317"
  trace_reporter_type: "OTLP"
```
## Proposal
Allow the OTLP span exporter endpoint config to take a value with or without the protocol specified.

If not protocol is specified, add 'http://' to the value passed to the OTLP exporter class.
